<?php

/**
 * BaseblogUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $name
 * @property string $pass
 * @property integer $messages
 * 
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method string    getName()     Returns the current record's "name" value
 * @method string    getPass()     Returns the current record's "pass" value
 * @method integer   getMessages() Returns the current record's "messages" value
 * @method blogUsers setUserId()   Sets the current record's "user_id" value
 * @method blogUsers setName()     Sets the current record's "name" value
 * @method blogUsers setPass()     Sets the current record's "pass" value
 * @method blogUsers setMessages() Sets the current record's "messages" value
 * @property  $created_at
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseblogUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_users');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('pass', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('messages', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_at', '', null);
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}