<?php

/**
 * BaseblogComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $commentary
 * @property string $photo
 * 
 * @method string       getCommentary() Returns the current record's "commentary" value
 * @method string       getPhoto()      Returns the current record's "photo" value
 * @method blogComments setCommentary() Sets the current record's "commentary" value
 * @method blogComments setPhoto()      Sets the current record's "photo" value
 * @property  $created_at
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseblogComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_comments');
        $this->hasColumn('commentary', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
        $this->hasColumn('photo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('created_at', '', null);
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}