<?php

/**
 * BaseblogPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $post
 * @property string $photo
 * 
 * @method string    getPost()  Returns the current record's "post" value
 * @method string    getPhoto() Returns the current record's "photo" value
 * @method blogPosts setPost()  Sets the current record's "post" value
 * @method blogPosts setPhoto() Sets the current record's "photo" value
 * @property  $created_at
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseblogPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_posts');
        $this->hasColumn('post', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5000,
             ));
        $this->hasColumn('photo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('created_at', '', null);
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}