<?php

/**
 * blogCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blogCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blogCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blogComments');
    }
}