<?php

/**
 * blogUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class blogUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object blogUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('blogUsers');
    }
}