<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/05 23:07:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => '106',
  'name' => 'doctrine',
)),);
