<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/31 21:43:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => '106',
  'name' => 'doctrine',
)),);
