<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/31 14:39:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
