<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/05/31 22:01:26
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinerecord' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfwidgetformdoctrinechoice' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineformgenerator' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinecli' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfvalidatordoctrinechoice' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfformdoctrine' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinepager' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinedqltask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedataloadtask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebasetask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinebuildtask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinedatadumptask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildschematask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebuildformstask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinemigratetask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinedropdbtask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedatabase' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfwebdebugpaneldoctrine' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sftesterdoctrine' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'swift_doctrinespool' => '/home/sfproject/blog/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',

  // project
  'baseform' => '/home/sfproject/blog/lib/form/BaseForm.class.php',
  'baseblogcommentsform' => '/home/sfproject/blog/lib/form/doctrine/base/BaseblogCommentsForm.class.php',
  'baseblogusersform' => '/home/sfproject/blog/lib/form/doctrine/base/BaseblogUsersForm.class.php',
  'baseblogpostsform' => '/home/sfproject/blog/lib/form/doctrine/base/BaseblogPostsForm.class.php',
  'blogusersform' => '/home/sfproject/blog/lib/form/doctrine/blogUsersForm.class.php',
  'blogcommentsform' => '/home/sfproject/blog/lib/form/doctrine/blogCommentsForm.class.php',
  'blogpostsform' => '/home/sfproject/blog/lib/form/doctrine/blogPostsForm.class.php',
  'baseformdoctrine' => '/home/sfproject/blog/lib/form/doctrine/BaseFormDoctrine.class.php',
  'blogpostsformfilter' => '/home/sfproject/blog/lib/filter/doctrine/blogPostsFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/sfproject/blog/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'blogusersformfilter' => '/home/sfproject/blog/lib/filter/doctrine/blogUsersFormFilter.class.php',
  'baseblogpostsformfilter' => '/home/sfproject/blog/lib/filter/doctrine/base/BaseblogPostsFormFilter.class.php',
  'baseblogcommentsformfilter' => '/home/sfproject/blog/lib/filter/doctrine/base/BaseblogCommentsFormFilter.class.php',
  'baseblogusersformfilter' => '/home/sfproject/blog/lib/filter/doctrine/base/BaseblogUsersFormFilter.class.php',
  'blogcommentsformfilter' => '/home/sfproject/blog/lib/filter/doctrine/blogCommentsFormFilter.class.php',

  // project_model
  'blogcomments' => '/home/sfproject/blog/lib/model/doctrine/blogComments.class.php',
  'blogpoststable' => '/home/sfproject/blog/lib/model/doctrine/blogPostsTable.class.php',
  'baseblogposts' => '/home/sfproject/blog/lib/model/doctrine/base/BaseblogPosts.class.php',
  'baseblogusers' => '/home/sfproject/blog/lib/model/doctrine/base/BaseblogUsers.class.php',
  'baseblogcomments' => '/home/sfproject/blog/lib/model/doctrine/base/BaseblogComments.class.php',
  'bloguserstable' => '/home/sfproject/blog/lib/model/doctrine/blogUsersTable.class.php',
  'blogcommentstable' => '/home/sfproject/blog/lib/model/doctrine/blogCommentsTable.class.php',
  'blogusers' => '/home/sfproject/blog/lib/model/doctrine/blogUsers.class.php',
  'blogposts' => '/home/sfproject/blog/lib/model/doctrine/blogPosts.class.php',

  // application
  'myuser' => '/home/sfproject/blog/apps/frontend/lib/myUser.class.php',

  // modules
);
