blogUsers:
  actAs: { Timestampable: ~ }
  columns:
#    id:         ~
    user_id:    { type: integer }
    name:       { type: string(255), notnull: true }
    pass:       { type: string(255), notnull:true }
    messages:   { type: integer }
    created_at: ~
 
blogPosts:
  actAs: { Timestampable: ~ }
  columns:
#    id:         ~
    post:       { type: string(5000), notnull: true }
    photo:      { type: string }
    created_at: ~
 
blogComments:
  actAs: { Timestampable: ~ }
  columns:
#    id:         ~
    commentary: { type: string(3000), notnull: true }
    photo:      { type: string }
    created_at: ~